name = "terminal-0-bingo"
main = "worker/index.ts"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat_v2"]

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]
