export type Player = {
  id: string;
  name: string;
  card: string[]; // 25 items
  marked: boolean[]; // 25 booleans (for bingo detection)
  seen: string[]; // List of items this player has marked as seen
  hasBingo: boolean;
};

export type GameState = {
  status: 'waiting' | 'playing' | 'ended';
  players: Player[];
  winner: string | null;
  roomCode: string;
  createdAt: number; // timestamp for 48-hour expiration
};

export type ClientMessage =
  | { type: 'JOIN'; name: string; roomCode?: string; savedPlayerId?: string }
  | { type: 'MARK'; index: number }
  | { type: 'TOGGLE_SEEN'; item: string }
  | { type: 'START' }
  | { type: 'REGENERATE_CARD' };

export type ServerMessage =
  | { type: 'STATE_UPDATE'; state: GameState }
  | { type: 'ERROR'; message: string }
  | { type: 'WELCOME'; playerId: string; roomCode: string };

// Terminal 0 Sightings - Mythical/weird things that should be in Terminal 0, but are in YOUR terminal

export const LOOKS_SIGHTINGS = [
  "Someone with glowing eyes",
  "A passenger phasing in and out of visibility",
  "Person with clockwork visible under their skin",
  "Someone whose shadow moves independently",
  "Passenger with too many fingers",
  "Someone who casts no reflection",
  "Person with backwards-facing knees",
  "Passenger whose face is slightly pixelated",
  "Someone with steam coming from their ears",
  "Person wearing clothes that shift colors constantly",
  "Passenger with antlers growing from their head",
  "Someone whose hair defies gravity",
  "Person with geometric patterns on their skin",
  "Passenger with eyes that are different species",
  "Someone with translucent skin",
  "Person whose outline is slightly blurred",
  "Passenger with wings folded under their jacket",
  "Someone with scales instead of skin",
  "Person with a third eye on their forehead",
  "Passenger whose age keeps changing",
  "Someone with bioluminescent tattoos",
  "Person with roots growing from their feet",
  "Passenger with mechanical joints visible",
  "Someone whose face is a screen",
  "Person with feathers instead of hair",
  "Passenger with crystalline fingernails",
  "Someone with smoke trailing behind them",
  "Person whose skin has a metallic sheen",
  "Passenger with pupils shaped like keyholes",
  "Someone with frost forming on their clothes",
  "Person with circuit board patterns on their arms",
  "Passenger whose teeth are all different colors",
  "Someone with flowers growing from their hair",
  "Person with a halo of static electricity",
  "Passenger whose skin changes texture",
  "Someone with eyes that glow in the dark",
  "Person with tentacles barely hidden",
  "Passenger with transparent eyelids",
  "Someone whose veins glow",
  "Person with moth wings on their back",
  "Passenger with horns filed down",
  "Someone whose hair is made of fiber optics",
  "Person with a tail tucked into their pants",
  "Passenger with kaleidoscope eyes",
  "Someone with bark-like skin",
  "Person whose ears are pointed",
  "Passenger with gills on their neck",
  "Someone with prismatic tears",
  "Person with too many joints in their fingers",
  "Passenger whose nose glows",
  "Someone with constellation freckles",
  "Person with iridescent skin",
  "Passenger whose hair moves like tentacles",
  "Someone with webbed fingers",
  "Person with eyes that change color with mood",
  "Passenger with a forked tongue",
  "Someone whose skin has QR code patterns",
  "Person with butterfly wings under their coat",
  "Passenger with fangs barely concealed",
  "Someone whose shadow is the wrong shape",
  "Person with LED eyelashes",
  "Passenger with fur peeking out from collar",
  "Someone whose freckles form constellations",
  "Person with chrome fingernails",
  "Passenger with extra thumbs",
  "Someone whose hair is on fire (but not burning)",
  "Person with holographic skin",
  "Passenger with snake eyes",
  "Someone whose ears twitch like an animal's",
  "Person with moss growing on their shoulders",
  "Passenger with neon-colored blood visible",
  "Someone whose teeth are too sharp",
  "Person with peacock feather hair",
  "Passenger with digitigrade legs",
  "Someone whose skin ripples like water",
  "Person with gemstone eyes",
  "Passenger with too many ribs visible",
  "Someone whose hair is made of grass",
  "Person with aurora borealis in their eyes",
  "Passenger with claws instead of nails",
  "Someone whose skin has hexagonal patterns",
  "Person with bioluminescent veins",
  "Passenger with compound eyes",
  "Someone whose hair floats upward",
  "Person with dragon scales on their neck",
  "Passenger with starlight in their pupils",
  "Someone whose skin is slightly see-through",
  "Person with runes carved into their skin",
  "Passenger with extra vertebrae visible",
  "Someone whose hair changes color with temperature",
  "Person with insect wings folded on back",
  "Passenger with mercury for blood",
  "Someone whose skin has binary code",
  "Person with owl eyes",
  "Passenger with thorns growing from their spine",
  "Someone whose fingernails are mirrors",
  "Person with jellyfish-like translucency",
  "Passenger with too many teeth",
  "Someone whose hair is made of ribbons of light",
];

export const BEHAVIOR_SIGHTINGS = [
  "Someone walking backwards perfectly",
  "Passenger having a conversation with nobody",
  "Person reading a book with blank pages intently",
  "Someone staring at a wall for 10+ minutes",
  "Passenger walking in perfect circles",
  "Person arguing with their luggage",
  "Someone counting ceiling tiles obsessively",
  "Passenger writing in the air with their finger",
  "Person bowing to every trash can",
  "Someone taking photos of nothing",
  "Passenger whispering to plants",
  "Person collecting dropped receipts",
  "Someone measuring everything with their hands",
  "Passenger drawing invisible symbols",
  "Person tasting the air repeatedly",
  "Someone walking only on specific floor tiles",
  "Passenger conducting an invisible orchestra",
  "Person having a full conversation in reverse",
  "Someone sniffing every surface",
  "Passenger reorganizing other people's belongings",
  "Person writing down every announcement",
  "Someone touching every window they pass",
  "Passenger counting their steps out loud",
  "Person saluting every uniform they see",
  "Someone collecting boarding passes from trash",
  "Passenger making origami from napkins obsessively",
  "Person tapping out morse code on surfaces",
  "Someone following the same person repeatedly",
  "Passenger reading signs backwards",
  "Person arranging coins in patterns",
  "Someone listening to walls with a cup",
  "Passenger walking heel-to-toe everywhere",
  "Person cataloging every sound they hear",
  "Someone spinning in place between gates",
  "Passenger leaving cryptic notes everywhere",
  "Person timing everything with a stopwatch",
  "Someone collecting ice from drink machines",
  "Passenger speaking only in questions",
  "Person walking in figure-eights constantly",
  "Someone photographing their own shadow",
  "Passenger rearranging waiting area chairs",
  "Person writing coordinates on napkins",
  "Someone measuring distances with string",
  "Passenger humming the same note for hours",
  "Person collecting airline magazines in order",
  "Someone walking only where shadows fall",
  "Passenger making maps of the terminal",
  "Person touching every door handle twice",
  "Someone counting passengers obsessively",
  "Passenger leaving pennies in specific spots",
  "Person recording ambient sounds",
  "Someone walking the same route repeatedly",
  "Passenger arranging sugar packets by color",
  "Person speaking to reflections",
  "Someone collecting lost buttons",
  "Passenger drawing floor plans constantly",
  "Person timing flights with precision",
  "Someone categorizing trash by type",
  "Passenger making rubbings of textured surfaces",
  "Person walking only clockwise",
  "Someone collecting baggage tags",
  "Passenger testing every chair for comfort",
  "Person documenting every smell",
  "Someone walking in prime number steps",
  "Passenger leaving coded messages",
  "Person collecting airline safety cards",
  "Someone measuring temperature everywhere",
  "Passenger walking in geometric patterns",
  "Person cataloging every logo they see",
  "Someone collecting plastic utensils",
  "Passenger counting light fixtures",
  "Person walking only on cracks",
  "Someone recording gate announcements",
  "Passenger arranging found objects in spirals",
  "Person touching every pillar three times",
  "Someone collecting napkins from different airlines",
  "Passenger walking in alphabetical gate order",
  "Person documenting every color they see",
  "Someone collecting receipts by timestamp",
  "Passenger making shadow puppets alone",
  "Person walking in Fibonacci sequences",
  "Someone cataloging every scent",
  "Passenger leaving origami in specific locations",
  "Person timing escalator rides precisely",
  "Someone collecting airline cups",
  "Passenger walking only in straight lines",
  "Person documenting every texture",
  "Someone arranging trash artistically",
  "Passenger counting steps between gates",
  "Person collecting boarding pass stubs",
  "Someone walking in musical note patterns",
  "Passenger leaving stones in corners",
  "Person documenting every reflection",
  "Someone collecting straws by color",
  "Passenger walking in constellation patterns",
  "Person timing bathroom visits",
  "Someone cataloging every pattern",
  "Passenger arranging chairs in sacred geometry",
  "Person collecting airline napkins",
  "Someone walking only during announcements",
];

export const SMELL_SIGHTINGS = [
  "Sudden smell of burnt toast",
  "Whiff of ozone and copper",
  "Scent of old books and dust",
  "Smell of petrichor indoors",
  "Aroma of cinnamon and static",
  "Odor of wet dog with no dog present",
  "Scent of fresh-cut grass in winter",
  "Smell of chlorine nowhere near a pool",
  "Aroma of vanilla and electricity",
  "Whiff of sulfur and roses",
  "Scent of ocean salt miles from coast",
  "Smell of burning rubber briefly",
  "Aroma of fresh bread at 3 AM",
  "Odor of mothballs and mint",
  "Scent of rain on hot pavement indoors",
  "Smell of campfire smoke inside",
  "Aroma of coffee and ozone",
  "Whiff of pine trees in the terminal",
  "Scent of hot metal and honey",
  "Smell of fresh paint constantly",
  "Aroma of lavender and diesel",
  "Odor of formaldehyde faintly",
  "Scent of popcorn with no source",
  "Smell of new car interior",
  "Aroma of sandalwood and plastic",
  "Whiff of ammonia and flowers",
  "Scent of parchment and ink",
  "Smell of burning incense",
  "Aroma of citrus and rust",
  "Odor of wet concrete",
  "Scent of jasmine at midnight",
  "Smell of hot asphalt indoors",
  "Aroma of sage and copper",
  "Whiff of gunpowder briefly",
  "Scent of fresh laundry everywhere",
  "Smell of maple syrup randomly",
  "Aroma of tobacco and vanilla",
  "Odor of bleach and roses",
  "Scent of woodsmoke persistently",
  "Smell of hospital disinfectant",
  "Aroma of peppermint and metal",
  "Whiff of gasoline faintly",
  "Scent of cherry blossoms in fall",
  "Smell of old leather",
  "Aroma of coconut and ozone",
  "Odor of vinegar and honey",
  "Scent of fresh snow indoors",
  "Smell of burning sugar",
  "Aroma of eucalyptus and plastic",
  "Whiff of formaldehyde and flowers",
  "Scent of wet wool",
  "Smell of caramel and copper",
  "Aroma of pine and diesel",
  "Odor of chlorine and vanilla",
  "Scent of burning leaves inside",
  "Smell of fresh paint and roses",
  "Aroma of cinnamon and rust",
  "Whiff of mothballs and mint",
  "Scent of hot tar",
  "Smell of lilac in winter",
  "Aroma of coffee and sulfur",
  "Odor of wet cardboard",
  "Scent of honeysuckle at night",
  "Smell of burning plastic briefly",
  "Aroma of vanilla and ammonia",
  "Whiff of old books",
  "Scent of fresh mulch indoors",
  "Smell of chocolate and ozone",
  "Aroma of sage and diesel",
  "Odor of formaldehyde and mint",
  "Scent of rain and metal",
  "Smell of burning hair faintly",
  "Aroma of lavender and copper",
  "Whiff of gasoline and flowers",
  "Scent of fresh bread and rust",
  "Smell of chlorine and roses",
  "Aroma of pine and plastic",
  "Odor of wet dog and vanilla",
  "Scent of campfire and honey",
  "Smell of hot metal persistently",
  "Aroma of cinnamon and bleach",
  "Whiff of sulfur and mint",
  "Scent of ocean and diesel",
  "Smell of burning rubber and roses",
  "Aroma of coffee and formaldehyde",
  "Odor of fresh paint and copper",
  "Scent of popcorn and ozone",
  "Smell of new car and flowers",
  "Aroma of sandalwood and rust",
  "Whiff of ammonia and vanilla",
  "Scent of parchment and metal",
  "Smell of incense and plastic",
  "Aroma of citrus and bleach",
  "Odor of wet concrete and roses",
  "Scent of jasmine and diesel",
  "Smell of asphalt and honey",
  "Aroma of sage and formaldehyde",
  "Whiff of gunpowder and flowers",
  "Scent of laundry and copper",
];

export const OBJECT_SIGHTINGS = [
  "Vending machine selling memories",
  "Clock running backwards",
  "Door that leads to the same room",
  "Escalator that goes sideways",
  "Trash can that's always empty",
  "Water fountain dispensing fog",
  "Chair that's always warm",
  "Window showing a different season",
  "Phone charging station sparking purple",
  "Baggage carousel going vertical",
  "Sign with text that changes when you look away",
  "Bathroom door that's a different color inside",
  "Vending machine with items from the future",
  "Bench that's slightly levitating",
  "Trash can that hums",
  "Water fountain with glowing water",
  "Clock with 13 hours",
  "Door handle that's always cold",
  "Escalator steps with runes",
  "Window that shows nighttime during day",
  "Phone booth that rings constantly",
  "Baggage carousel with no beginning or end",
  "Sign written in unknown language",
  "Bathroom mirror that shows yesterday",
  "Vending machine accepting only buttons",
  "Bench made of impossible geometry",
  "Trash can that whispers",
  "Water fountain flowing upward",
  "Clock with hands moving at different speeds",
  "Door that's warm to the touch",
  "Escalator that hums a melody",
  "Window showing a different airport",
  "Phone charger with crystalline growth",
  "Baggage carousel rotating wrong direction",
  "Sign that glows from within",
  "Bathroom with too many stalls inside",
  "Vending machine with living plants",
  "Bench that's always in shadow",
  "Trash can that's bigger inside",
  "Water fountain with geometric ice",
  "Clock showing multiple time zones wrong",
  "Door with no visible hinges",
  "Escalator with steps that shimmer",
  "Window that fogs from the outside",
  "Phone booth from the 1950s working",
  "Baggage carousel with ancient luggage",
  "Sign pointing to non-existent gates",
  "Bathroom door that's always locked but open",
  "Vending machine with expired items from 2050",
  "Bench with carved warnings",
  "Trash can that's never full",
  "Water fountain with prismatic spray",
  "Clock with Roman numerals in wrong order",
  "Door that opens before you touch it",
  "Escalator with missing steps that work",
  "Window showing stars during daytime",
  "Phone charging cables that move",
  "Baggage carousel with fog inside",
  "Sign with arrows pointing at each other",
  "Bathroom with infinite mirror reflections",
  "Vending machine dispensing mist",
  "Bench that's always occupied by shadows",
  "Trash can with bioluminescent interior",
  "Water fountain that never stops running",
  "Clock face with symbols instead of numbers",
  "Door that's different sizes from each side",
  "Escalator that changes speed randomly",
  "Window that shows the same plane repeatedly",
  "Phone booth with rotary dial glowing",
  "Baggage carousel with items appearing from nowhere",
  "Sign that reflects light wrong",
  "Bathroom with doors that don't match stalls",
  "Vending machine with crystallized snacks",
  "Bench with frost forming on it",
  "Trash can that echoes",
  "Water fountain with geometric patterns in flow",
  "Clock that ticks backwards occasionally",
  "Door with handle on both sides same place",
  "Escalator with holographic steps",
  "Window showing aurora borealis",
  "Phone charger sparking different colors",
  "Baggage carousel with luggage phasing through",
  "Sign with text in multiple dimensions",
  "Bathroom with impossible acoustics",
  "Vending machine with items rearranging themselves",
  "Bench that's always the perfect temperature",
  "Trash can with items disappearing",
  "Water fountain with water that doesn't wet",
  "Clock with hands that occasionally stop",
  "Door that sounds hollow on both sides",
  "Escalator with steps that glow",
  "Window showing different weather each pane",
  "Phone booth that smells like ozone",
  "Baggage carousel with shadows but no luggage",
  "Sign that points to itself",
  "Bathroom with stalls bigger than the room",
  "Vending machine with items from different eras",
  "Bench with inscriptions that change",
  "Trash can that's always slightly vibrating",
  "Water fountain with fractal ice formations",
];

// Combined pool for backward compatibility and random selection
export const ALL_SIGHTINGS = [
  ...LOOKS_SIGHTINGS,
  ...BEHAVIOR_SIGHTINGS,
  ...SMELL_SIGHTINGS,
  ...OBJECT_SIGHTINGS,
];
