export type Player = {
  id: string;
  name: string;
  card: string[]; // 25 items
  marked: boolean[]; // 25 booleans
  hasBingo: boolean;
};

export type GameState = {
  status: 'waiting' | 'playing' | 'ended';
  players: Player[];
  calledItems: string[];
  winner: string | null;
  roomCode: string;
};

export type ClientMessage =
  | { type: 'JOIN'; name: string; roomCode?: string }
  | { type: 'MARK'; index: number }
  | { type: 'START' }
  | { type: 'CALL_ITEM' }
  | { type: 'REGENERATE_CARD' };

export type ServerMessage =
  | { type: 'STATE_UPDATE'; state: GameState }
  | { type: 'ERROR'; message: string }
  | { type: 'WELCOME'; playerId: string; roomCode: string };

export const SIGHTINGS = [
  "A passenger who is clearly a time traveler",
  "Someone wearing sunglasses indoors at night",
  "A gate that wasn't there yesterday",
  "Luggage wrapped in tinfoil",
  "A pilot reading a suspicious manual",
  "The smell of ozone and old books",
  "An escalator going to nowhere",
  "Someone arguing with a reflection",
  "Ticket printed on something unusual",
  "Unattended baggage that is vibrating",
  "Pilot who looks exactly like you",
  "Someone reading a very old newspaper",
  "A pet in an unusual carrier",
  "Luggage carousel going the wrong way",
  "Someone wearing a costume casually",
  "A passenger with too many carry-ons",
  "Someone sleeping in an impossible position",
  "A child running in the opposite direction of their parent",
  "Someone talking to themselves intensely",
  "A passenger wearing pajamas",
  "Someone with an exotic pet",
  "A person doing yoga in the terminal",
  "Someone wearing a full suit of armor (cosplay)",
  "A passenger with a musical instrument bigger than them",
  "Someone eating a whole pizza alone",
  "A person wearing winter clothes in summer",
  "Someone with a suspiciously large hat",
  "A passenger knitting something enormous",
  "Someone reading a map upside down",
  "A person wearing mismatched shoes",
  "Someone with a plant as carry-on",
  "A passenger doing tai chi",
  "Someone wearing a cape",
  "A person with an unusual number of neck pillows",
  "Someone carrying a surfboard to a landlocked destination",
  "A passenger wearing a tiara",
  "Someone with a typewriter",
  "A person juggling while walking",
  "Someone wearing a snorkel and flippers",
  "A passenger with a boombox",
  "Someone dressed as a pilot who isn't a pilot",
  "A person wearing a monocle",
  "Someone with a parrot on their shoulder",
  "A passenger wearing roller skates",
  "Someone reading a book that's clearly upside down",
  "A person with a fishing rod",
  "Someone wearing a top hat",
  "A passenger with a ukulele",
  "Someone in a wedding dress",
  "A person wearing a snuggie",
  "Someone with a hula hoop",
  "A passenger wearing a onesie",
  "Someone with a didgeridoo",
  "A person in a bathrobe",
  "Someone wearing a fanny pack as a crossbody",
  "A passenger with a bongo drum",
  "Someone in full hiking gear",
  "A person wearing a tutu",
  "Someone with a metal detector",
  "A passenger wearing a cowboy hat indoors",
  "Someone with a telescope",
  "A person in a tracksuit with no intention of exercising",
  "Someone wearing a lei",
  "A passenger with a skateboard as luggage",
  "Someone in a business suit wearing flip-flops",
  "A person with a mandolin",
  "Someone wearing a sombrero",
  "A passenger with a boomerang",
  "Someone in scrubs not going to/from work",
  "A person wearing a bow tie with a t-shirt",
  "Someone with a didgeridoo case",
  "A passenger wearing a kilt",
  "Someone with a banjo",
  "A person in a tuxedo t-shirt",
  "Someone wearing a fedora unironically",
  "A passenger with a harmonica",
  "Someone in a leisure suit",
  "A person wearing a beret",
  "Someone with a accordion",
  "A passenger wearing crocs with socks",
  "Someone in a velour tracksuit",
  "A person wearing a visor backwards",
  "Someone with a tambourine",
  "A passenger wearing a bucket hat",
  "Someone in head-to-toe denim",
  "A person wearing a headlamp indoors",
  "Someone with a kazoo",
  "A passenger wearing a poncho indoors",
  "Someone in a Hawaiian shirt in winter",
  "A person wearing a sleeping mask on their forehead",
  "Someone with a recorder (the instrument)",
  "A passenger wearing a life vest",
  "Someone in camouflage in an airport",
  "A person wearing a shower cap",
  "Someone with a triangle (the instrument)",
  "A passenger wearing a snorkel (just the snorkel)",
  "Someone in a Christmas sweater in July",
  "A person wearing a headband with antennae",
  "Someone with a xylophone",
  "A passenger wearing a name tag that says 'Hello, I'm Lost'",
  "Someone in a jersey for a team that doesn't exist",
  "A person wearing a cape and no costume",
  "Someone with a gong",
  "A passenger wearing a tool belt with no tools",
  "Someone in a lab coat casually",
  "A person wearing a crown from Burger King",
  "Someone with a theremin",
  "A passenger wearing a referee shirt",
  "Someone in a mascot head (just the head)",
  "A person wearing a sash for no reason",
  "Someone with a melodica",
  "A passenger wearing a badge that says 'Official'",
  "Someone in a choir robe",
  "A person wearing a lei made of something weird",
  "Someone with a rain stick",
  "A passenger wearing a lanyard with 50+ badges",
  "Someone in a graduation gown",
  "A person wearing a fake mustache",
  "Someone with a pan flute",
  "A passenger wearing a whistle around their neck",
  "Someone in a karate gi",
  "A person wearing a propeller hat",
  "Someone with a hurdy-gurdy",
  "A passenger wearing a clown nose",
  "Someone in a choir outfit",
  "A person wearing a viking helmet",
  "Someone with a lute",
  "A passenger wearing a superhero mask",
  "Someone in a marching band uniform",
  "A person wearing a fake beard",
  "Someone with a sitar",
  "A passenger wearing a pirate eye patch",
  "Someone in a Renaissance fair costume",
  "A person wearing a jester hat",
  "Someone with a bagpipe",
  "A passenger wearing a plague doctor mask",
  "Someone in a sumo wrestler costume",
  "A person wearing a unicorn horn headband",
  "Someone with a harp (small)",
  "A passenger wearing a ninja headband",
  "Someone in a Elvis costume",
  "A person wearing a cat ear headband",
  "Someone with a zither",
  "A passenger wearing a Groucho Marx disguise",
  "Someone in a disco outfit",
  "A person wearing a traffic cone as a hat",
  "Someone with a dulcimer",
  "A passenger wearing a chicken hat",
  "Someone in a 70s leisure suit",
  "A person wearing a fruit hat",
  "Someone with a concertina",
  "A passenger wearing a lobster bib",
  "Someone in a safari outfit",
  "A person wearing a cheese head",
  "Someone with a ocarina",
  "A passenger wearing a beer hat",
  "Someone in a matador costume",
  "A person wearing a lampshade as a hat",
  "Someone with a kalimba",
  "A passenger wearing a foam finger",
  "Someone in a astronaut costume",
  "A person wearing a colander as a hat",
  "Someone with a melodeon",
  "A passenger wearing a horse head mask",
  "Someone in a mime costume",
  "A person wearing a shower curtain as a cape",
  "Someone with a autoharp",
  "A passenger wearing a banana costume",
  "Someone in a gorilla suit",
  "A person wearing a traffic vest fashionably",
  "Someone with a mandola",
  "A passenger wearing a hotdog costume",
  "Someone in a dinosaur costume",
  "A person wearing a construction hat backwards",
  "Someone with a bouzouki",
  "A passenger wearing a inflatable costume",
  "Someone in a chicken costume",
  "A person wearing a welding mask as sunglasses",
  "Someone with a cittern",
  "A passenger wearing a taco costume",
  "Someone in a cow costume",
  "A person wearing a hazmat suit casually",
  "Someone with a theorbo",
  "A passenger wearing a pizza costume",
  "Someone in a penguin costume",
  "A person wearing a gas mask as a fashion statement",
  "Someone with a vihuela",
  "A passenger wearing a avocado costume",
  "Someone in a shark costume",
  "A person wearing a scuba mask on their head",
  "Someone with a charango",
  "A passenger wearing a pineapple costume",
  "Someone in a unicorn costume",
  "A person wearing a snorkel and mask (no water nearby)",
  "Someone with a cuatro",
  "A passenger wearing a cactus costume",
  "Someone in a sloth costume",
  "A person wearing ski goggles indoors",
  "Someone with a tres",
  "A passenger wearing a donut costume",
  "Someone in a llama costume"
];
